sudo: false
dist: trusty

branches:
  only:
    - master

matrix:
  include:
    - env: PYTHON=3.5 CONDA_PY=35 QT_VERSION=5
    - env: PYTHON=3.6 CONDA_PY=36 QT_VERSION=5

before_install:

  # Install Miniconda
  - travis_retry wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/anaconda
  - export PATH=~/anaconda/bin:$PATH

  # Setup environment
  - travis_retry conda update --yes conda
  - conda config --set always_yes yes
  - conda config --append channels conda-forge
  - conda install conda-build anaconda-client -q
  - conda info -a
  - conda create -n travisci python=$PYTHON pip
  - source activate travisci
  - CONDA_INSTALL="conda install -q"
  - PIP_INSTALL="pip install -q"

  # Setup conda build output directory
  - cd ~
  - mkdir conda-bld-out
  - cd conda-bld-out
  - export CONDA_BLD_PATH=$(pwd)

  # Install exopy dependencies
  - $CONDA_INSTALL pyqt=$QT_VERSION numpy lmfit pyvisa

install:
  # Build conda package and install it (check that build script is not broken)
  - cd $TRAVIS_BUILD_DIR
  - conda build conda -q  # Package building does run only very minimal tests
  - conda install exopy --use-local -q
  - cd ~

script:
  - echo "Test test test"
